import React from 'react';
import DocumentStatusBadge from './DocumentStatusBadge';
import { tokenStorage } from '../../../services/crmApi';
import { BASE_URL } from '../../../constants/crm';

export default function DocumentPreview({ document, onClose }) {
    if (!document) return null;

    const token = tokenStorage.getAccessToken() || '';
    const downloadUrl = `${BASE_URL}/admin/documents/${document.documentId}?download=true&token=${token}`;

    return (
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div>
                    <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
                        📄 {document.documentType}
                        <DocumentStatusBadge status={document.status} />
                    </h3>
                    <div className="text-xs font-mono text-slate-400 mt-0.5">
                        ID: {document.documentId} | Version: V{document.version || 1}
                    </div>
                </div>
                <button
                    onClick={onClose}
                    className="text-xs text-slate-400 hover:text-slate-200 px-2 py-1 bg-slate-800 rounded"
                >
                    ✕ Close
                </button>
            </div>

            <div className="grid grid-cols-2 gap-4 text-xs bg-slate-900/60 p-3 rounded-lg border border-slate-800">
                <div><span className="text-slate-400">File Name:</span> <span className="font-mono text-slate-200">{document.fileName}</span></div>
                <div><span className="text-slate-400">Checksum (SHA-256):</span> <span className="font-mono text-slate-400 text-[10px]">{document.checksum ? document.checksum.substring(0, 16) + '...' : 'N/A'}</span></div>
                <div><span className="text-slate-400">Generated By:</span> <span className="text-slate-200">{document.generatedBy} ({document.generatedByRole})</span></div>
                <div><span className="text-slate-400">Storage Provider:</span> <span className="font-mono text-orange-400">{document.storageProvider}</span></div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-2">
                <a
                    href={downloadUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="px-4 py-2 bg-orange-500 text-slate-950 font-bold rounded-lg text-xs hover:bg-orange-400 transition-colors inline-block"
                >
                    ⬇️ Download PDF
                </a>
            </div>
        </div>
    );
}
